@TMSAPI_HostAddress = http://localhost:5150

# GET {{TMSAPI_HostAddress}}/
# GET {{TMSAPI_HostAddress}}/weatherforecast/
GET {{TMSAPI_HostAddress}}/api/assessments/results/
# GET {{TMSAPI_HostAddress}}/api
# GET {{TMSAPI_HostAddress}}
Accept: application/json

###
