@TMSAPI_HostAddress = http://localhost:5150

# GET {{TMSAPI_HostAddress}}/
# GET {{TMSAPI_HostAddress}}/weatherforecast/
GET {{TMSAPI_HostAddress}}/api/assessments/results/

### 2. GET /api/enrollments
### Expected: 200 OK with empty array [] (no enrollments yet)
GET  http://localhost:5150/api/enrollments



# GET {{TMSAPI_HostAddress}}/api
# GET {{TMSAPI_HostAddress}}
Accept: application/json


###
GET  http://localhost:5150/api/enrollments/46135946

# POST http://localhost:5150/api/enrollments/
# GET http://localhost:5150/api/enrollments
# GET http://localhost:5150/api/enrollments/0ec9d453  getbyId 